### PR TITLE
UIKit support

### PR DESCRIPTION
**Pull request by aringenbach**
Adds UIKit support, a UIKit example app, expand test suite to run on both UIKit and SwiftUI implementations as well as a bit of documentation.

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
Both the `testTypingAndDeleting` seemed to be a bit flaky when I tested them. Otherwise, LGTM!

**Comment by aringenbach** [comment]
@jmartinesp Do you mean they failed the very first time and succeeded if relaunched ?

I think this is due to unreachable keyboard because of the keyboard swipe tutorial on first use (if you haven't yet used a textView with that simulator)

**Comment by jmartinesp** [comment]
> @jmartinesp Do you mean they failed the very first time and succeeded if relaunched ?
> 
> I think this is due to unreachable keyboard because of the keyboard swipe tutorial on first use (if you haven't yet used a textView with that simulator)

Actually, they just sometime work and others don't, especially `WysiwygUIKitTests.testTypingAndDeleting`:

<details>
<summary>Click to expand</summary>
```
Test Case '-[WysiwygUITests.WysiwygUIKitTests testTypingAndDeleting]' started.
    t =     0.00s Start Test at 2022-08-03 16:55:23.338
    t =     0.02s Set Up
    t =     0.02s     Open org.matrix.WysiwygUIKit
    t =     0.03s         Launch org.matrix.WysiwygUIKit
    t =     0.03s             Terminate org.matrix.WysiwygUIKit:42155
    t =     1.67s             Setting up automation session
    t =     2.13s             Wait for org.matrix.WysiwygUIKit to idle
    t =     3.18s Tap "WysiwygComposer" TextView
    t =     3.18s     Wait for org.matrix.WysiwygUIKit to idle
    t =     3.19s     Find the "WysiwygComposer" TextView
    t =     3.22s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     3.23s     Synthesize event
    t =     3.31s     Wait for org.matrix.WysiwygUIKit to idle
    t =     3.42s Type 'abc🎉🎉👩🏿‍🚀' into "WysiwygComposer" TextView
    t =     3.42s     Wait for org.matrix.WysiwygUIKit to idle
    t =     3.90s     Find the "WysiwygComposer" TextView
    t =     3.93s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     3.94s     Synthesize event
    t =     4.09s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.10s Find the "WysiwygComposer" TextView
    t =     4.12s Tap "delete" Key
    t =     4.12s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.13s     Find the "delete" Key
    t =     4.14s     Check for interrupting elements affecting "delete" Key
    t =     4.16s     Synthesize event
    t =     4.24s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.26s Find the "WysiwygComposer" TextView
    t =     4.28s Type '' into "WysiwygComposer" TextView
    t =     4.28s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.29s     Find the "WysiwygComposer" TextView
    t =     4.30s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     4.32s     Synthesize event
    t =     4.37s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.38s Find the "WysiwygComposer" TextView
    t =     4.40s Type 'cde 🥳 fgh' into "WysiwygComposer" TextView
    t =     4.40s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.40s     Find the "WysiwygComposer" TextView
    t =     4.42s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     4.43s     Synthesize event
    t =     4.60s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.61s Find the "WysiwygComposer" TextView
    t =     4.62s Double tap "WysiwygComposer" TextView
    t =     4.62s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.63s     Find the "WysiwygComposer" TextView
    t =     4.65s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     4.66s     Synthesize event
    t =     4.74s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.76s Tap "delete" Key
    t =     4.76s     Wait for org.matrix.WysiwygUIKit to idle
    t =     4.78s     Find the "delete" Key
    t =     4.80s     Check for interrupting elements affecting "delete" Key
    t =     4.82s     Synthesize event
    t =     4.91s     Wait for org.matrix.WysiwygUIKit to idle
    t =     5.18s Find the "WysiwygComposer" TextView
    t =     5.21s Tap "WysiwygComposer" TextView with 3 taps and 1 touch
    t =     5.21s     Wait for org.matrix.WysiwygUIKit to idle
    t =     5.23s     Find the "WysiwygComposer" TextView
    t =     5.25s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     5.27s     Synthesize event
    t =     5.36s     Wait for org.matrix.WysiwygUIKit to idle
    t =     5.62s Tap "delete" Key
    t =     5.62s     Wait for org.matrix.WysiwygUIKit to idle
    t =     5.63s     Find the "delete" Key
    t =     5.66s     Check for interrupting elements affecting "delete" Key
    t =     5.68s     Synthesize event
    t =     5.76s     Wait for org.matrix.WysiwygUIKit to idle
    t =     5.77s Find the "WysiwygComposer" TextView
/Users/arasthel/Developer/Element/wysiwyg/wysiwyg-rust/platforms/ios/example/WysiwygUITests/WysiwygSharedTests.swift:52: error: -[WysiwygUITests.WysiwygUIKitTests testTypingAndDeleting] : XCTAssertEqual failed: ("Optional("abcde 🥳 ")") is not equal to ("Optional("")")
    t =     5.83s Tear Down
```
</details>

Although this time `WysiwygUITests.testTypingAndDeleting` failed too. I'm testing it on the selected by default simulator (iPod Touch 7th gen iOS 15.5), I can try with other simulators just in case.

<details>
<summary>Click to expand</summary>
```
Test Case '-[WysiwygUITests.WysiwygUITests testTypingAndDeleting]' started.
    t =     0.00s Start Test at 2022-08-03 16:55:41.763
    t =     0.02s Set Up
    t =     0.02s     Open org.matrix.Wysiwyg
    t =     0.04s         Launch org.matrix.Wysiwyg
    t =     0.04s             Terminate org.matrix.Wysiwyg:42264
    t =     1.70s             Setting up automation session
    t =     2.11s             Wait for org.matrix.Wysiwyg to idle
    t =     3.17s Tap "WysiwygComposer" TextView
    t =     3.17s     Wait for org.matrix.Wysiwyg to idle
    t =     3.19s     Find the "WysiwygComposer" TextView
    t =     3.22s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     3.22s     Synthesize event
    t =     3.30s     Wait for org.matrix.Wysiwyg to idle
    t =     3.40s Type 'abc🎉🎉👩🏿‍🚀' into "WysiwygComposer" TextView
    t =     3.40s     Wait for org.matrix.Wysiwyg to idle
    t =     3.88s     Find the "WysiwygComposer" TextView
    t =     3.91s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     3.93s     Synthesize event
    t =     4.07s     Wait for org.matrix.Wysiwyg to idle
    t =     4.08s Find the "WysiwygComposer" TextView
    t =     4.09s Tap "delete" Key
    t =     4.09s     Wait for org.matrix.Wysiwyg to idle
    t =     4.10s     Find the "delete" Key
    t =     4.12s     Check for interrupting elements affecting "delete" Key
    t =     4.13s     Synthesize event
    t =     4.21s     Wait for org.matrix.Wysiwyg to idle
    t =     4.22s Find the "WysiwygComposer" TextView
/Users/arasthel/Developer/Element/wysiwyg/wysiwyg-rust/platforms/ios/example/WysiwygUITests/WysiwygSharedTests.swift:34: error: -[WysiwygUITests.WysiwygUITests testTypingAndDeleting] : XCTAssertEqual failed: ("Optional("abc🎉🎉👩🏿‍🚀")") is not equal to ("Optional("abc🎉🎉")")
    t =     4.25s Tear Down
Test Case '-[WysiwygUITests.WysiwygUITests testTypingAndDeleting]' failed (4.460 seconds).
Test Case '-[WysiwygUITests.WysiwygUITests testTypingAndSending]' started.
    t =     0.00s Start Test at 2022-08-03 16:55:46.223
    t =     0.02s Set Up
    t =     0.02s     Open org.matrix.Wysiwyg
    t =     0.03s         Launch org.matrix.Wysiwyg
    t =     0.03s             Terminate org.matrix.Wysiwyg:42268
    t =     1.47s             Setting up automation session
    t =     1.99s             Wait for org.matrix.Wysiwyg to idle
    t =     3.04s Tap "WysiwygComposer" TextView
    t =     3.04s     Wait for org.matrix.Wysiwyg to idle
    t =     3.05s     Find the "WysiwygComposer" TextView
    t =     3.08s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     3.09s     Synthesize event
    t =     3.17s     Wait for org.matrix.Wysiwyg to idle
    t =     3.26s Type 'Some bold text' into "WysiwygComposer" TextView
    t =     3.26s     Wait for org.matrix.Wysiwyg to idle
    t =     3.75s     Find the "WysiwygComposer" TextView
    t =     3.77s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     3.78s     Synthesize event
    t =     4.08s     Wait for org.matrix.Wysiwyg to idle
    t =     4.08s Double tap "WysiwygComposer" TextView
    t =     4.08s     Wait for org.matrix.Wysiwyg to idle
    t =     4.09s     Find the "WysiwygComposer" TextView
    t =     4.11s     Check for interrupting elements affecting "WysiwygComposer" TextView
    t =     4.12s     Synthesize event
    t =     4.20s     Wait for org.matrix.Wysiwyg to idle
    t =     5.22s Tap "WysiwygBoldButton" Button
    t =     5.22s     Wait for org.matrix.Wysiwyg to idle
    t =     5.24s     Find the "WysiwygBoldButton" Button
    t =     5.28s     Check for interrupting elements affecting "WysiwygBoldButton" Button
    t =     5.30s     Synthesize event
    t =     5.38s     Wait for org.matrix.Wysiwyg to idle
    t =     6.52s Tap "WysiwygSendButton" Button
    t =     6.53s     Wait for org.matrix.Wysiwyg to idle
    t =     6.55s     Find the "WysiwygSendButton" Button
    t =     6.58s     Check for interrupting elements affecting "WysiwygSendButton" Button
    t =     6.59s     Synthesize event
    t =     6.67s     Wait for org.matrix.Wysiwyg to idle
    t =     6.69s Find the "WysiwygContentText" StaticText
    t =     6.70s Tear Down
```
</details>

**Comment by jmartinesp** [comment]
Well, I killed the iPod simulator, tested it on an iPad Pro one, it worked every single time, came back to the iPod simulator and now it's consistently working fine 🤷 . I guess it was some kind of simulator issue.

**Pull request merged**
